#!/usr/bin/env bash
# Wrap vendor/markdown-it.min.js (UMD) as a QML ".pragma library" module exposing `markdownit`.
# QML JS has no module system, so the UMD gets a CommonJS shim. Re-run after updating the vendor file.
set -euo pipefail
cd "$(dirname "$0")/../.."
{
  echo '.pragma library'
  echo '// GENERATED by scripts/dev/build-mdit.sh from vendor/markdown-it.min.js (MIT, see vendor/markdown-it.LICENSE)'
  echo 'var __module = { exports: {} };'
  echo '(function (module, exports) {'
  cat vendor/markdown-it.min.js
  echo
  echo '}).call({}, __module, __module.exports);'
  echo 'var markdownit = __module.exports;'
} > js/mdit.js
echo "wrote js/mdit.js ($(wc -c < js/mdit.js) bytes)"
